name: app_template
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^12.0.0
  flutter_svg: ^2.0.8
  flutter_native_splash: ^2.3.4
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  quickalert: ^1.0.2
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  firebase_ui_auth: ^1.9.1
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_dynamic_links: ^5.4.2
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  firebase_ui_oauth_google: ^1.2.13
  firebase_ui_oauth_facebook: ^1.2.13
  flutter_dotenv: ^5.1.0
  firebase_remote_config: ^4.3.3
  firebase_analytics: ^10.6.3
  cloud_firestore: ^4.12.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
